services:
  - type: web
    name: drive-linker
    env: python
    buildCommand: ""
    startCommand: "python drive_airtable_email.py"
    envVars:
      - key: AIRTABLE_API_KEY
        fromEnv: AIRTABLE_API_KEY
      - key: AIRTABLE_BASE_ID
        fromEnv: AIRTABLE_BASE_ID
      - key: AIRTABLE_TABLE_NAME
        fromEnv: AIRTABLE_TABLE_NAME
      - key: SMTP_USER
        fromEnv: SMTP_USER
      - key: SMTP_PASS
        fromEnv: SMTP_PASS
      - key: DRIVE_FOLDER_ID
        fromEnv: DRIVE_FOLDER_ID
      - key: TRIGGER_TOKEN
        fromEnv: TRIGGER_TOKEN
